name: conecta_shopping_online
description: "Aplicativo de loja online utilizando Flutter e Firebase."

# Previne publicação acidental no pub.dev
publish_to: 'none'

# Versão do aplicativo
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Ícones no estilo iOS
  cupertino_icons: ^1.0.5

  # Dependências Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  firebase_analytics: ^11.3.6
  firebase_storage: ^12.3.7
  firebase_messaging: ^15.1.6
  cloud_firestore: ^5.5.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Conjunto de boas práticas recomendadas
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
