// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1nR0sAtlPByRw_tjQJgnXrpXKFvJJ7iY',
    appId: '1:866599133190:android:b9641af07ce48da3706387',
    messagingSenderId: '866599133190',
    projectId: 'conectashoponline',
    storageBucket: 'conectashoponline.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4fSqg1TA_l78_OWHK-1FJ7198UzxIk2Q',
    appId: '1:866599133190:ios:1a0c10127cd209d0706387',
    messagingSenderId: '866599133190',
    projectId: 'conectashoponline',
    storageBucket: 'conectashoponline.firebasestorage.app',
    iosBundleId: 'com.example.conectaShoppingOnline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4fSqg1TA_l78_OWHK-1FJ7198UzxIk2Q',
    appId: '1:866599133190:ios:1a0c10127cd209d0706387',
    messagingSenderId: '866599133190',
    projectId: 'conectashoponline',
    storageBucket: 'conectashoponline.firebasestorage.app',
    iosBundleId: 'com.example.conectaShoppingOnline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIsZS5VJmF7rWa9oZ66jjlv56e5OssSeE',
    appId: '1:866599133190:web:b0f090024783a911706387',
    messagingSenderId: '866599133190',
    projectId: 'conectashoponline',
    authDomain: 'conectashoponline.firebaseapp.com',
    storageBucket: 'conectashoponline.firebasestorage.app',
    measurementId: 'G-Z4NH5D00B0',
  );

}